version: '3.3'
services:
  web:
    restart: always
    build: ./app
    env_file: .env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5000"
    links:
      - postgres:postgres
    volumes:
      - ./app:/usr/src/app
      - ./app/static/:/usr/src/app/static
    command: uwsgi --socket :5000 --module app_name.wsgi
  nginx:
    restart: always
    image: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./app/static/:/var/www/static
    links:
      - web:web
  postgres:
    restart: always
    image: postgres
    build: ./postgres
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - "dbdata:/var/lib/postgresql/data" 
    ports:
     - "5432:5432"
volumes:
  dbdata:
#    image: postgres
  #webpack:
  #  build:
  #    context: ./webpack
  #  image: reactjs_webpack
  #  container_name: reactjs_webpack_container
  #  volumes:
  #    - ./app/src:/app/src:ro
  #    - ./app/dist:/app/dist:z
