version: '2'
services:
  web:
   restart: always
   build: ./app
   expose:
     - "5000"
   links:
     - postgres:postgres
   volumes:
     - ./app:/usr/src/app
     - ./app/static/:/usr/src/app/static
   command: uwsgi --socket :5000 --module ruroufumi.wsgi
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
    volumes_from:
      - web
    links:
      - web:web
  postgres:
   image: postgres
   build: ./postgres
   ports:
     - "5432:5432"
  #webpack:
  #  build:
  #    context: ./webpack
  #  image: reactjs_webpack
  #  container_name: reactjs_webpack_container
  #  volumes:
  #    - ./app/src:/app/src:ro
  #    - ./app/dist:/app/dist:z
